version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgresql_event_manage
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    restart: always

  api:
    image: node:alpine
    container_name: node_event_manage
    restart: always
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    working_dir: /usr/app
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: sh -c "npm install && npx prisma migrate deploy && npm run start:${NODE_ENV}"
    depends_on:
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${DB_PORT}/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      DEBUG: ${DEBUG}

volumes:
  postgres_data:  